#!/bin/sh -e

if [ ! -f .env ]; then
    echo "Copying .env.example to .env"
    cp .env.example .env
fi

echo "Installing dependencies with uv"
uv sync

echo "Installing plain pre-commit hooks"
uv run plain pre-commit --install
